# -*- mode: ruby -*-
# vi: set ft=ruby :

servers = [
  { 
    :hostname => "master",    
    :box => 'ubuntu/trusty64',
    :ip => '192.168.33.70',
    :ram => 2048,
    :cpus => 2
  },
  {
      :hostname => "slave1",
      :box => 'ubuntu/trusty64',
      :ip => '192.168.33.71',
      :ram => 2048,
      :cpus => 2
  },
  {
      :hostname => "slave2",
      :box => 'ubuntu/trusty64',
      :ip => '192.168.33.72',
      :ram => 2048,
      :cpus => 2
  }
]

Vagrant.configure(2) do |config|

    config.vm.provision "shell" do |s|
        s.path = "scripts/equip_base.sh"
    end

    # Install Oracle JDK 8
    config.vm.provision "shell" do |s|
        s.path = "scripts/equip_java8_wget.sh"
    end

    # Install Maven
    config.vm.provision "shell" do |s|
        s.path = "scripts/equip_maven3.sh"
    end

    # Install Docker
    config.vm.provision "shell" do |s|
        s.path = "scripts/equip_docker.sh"
    end

    # Add hadoop user
    config.vm.provision "shell" do |s|
        s.path = "scripts/equip_sudo_users.sh"
        s.args = "hadoop hadoop"
    end

    # Install hadoop
    config.vm.provision "shell" do |s|
        s.path = "scripts/setup_hadoop.sh"
    end

    servers.each do |machine|
        vm_name = "%s-%s" % ["docker_on_yarn", machine[:hostname]]
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.host_name = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.provider "virtualbox" do |vb|
                vb.name = vm_name
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
                vb.customize ["modifyvm", :id, "--cpus", machine[:cpus]]
                # Enable NAT DNS resolve
                vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
                # For bridge docker container
                vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']
            end
        end
    end
end
