version: '2'

services:
  zookeeper:
    image: ogre/zookeeper:3.4.8
    #container_name: zookeeper
    hostname: zookeeper
    dns:
      - 192.168.33.20
    environment:
      SERVICE_NAME: zk


  nimbus:
    image: ogre/storm-docker:1.0.1
    #container_name: nimbus
    hostname: nimbus
    depends_on:
      - zookeeper
    dns:
      - 192.168.33.20
    environment:
      SERVICE_NAME: nimbus
      NIMBUS_SERVICE_NAME: $nimbus
      ZK_SERVICE_NAME: $zookeeper
    command: --daemon nimbus

  ui:
    image: ogre/storm-docker:1.0.1
    #container_name: ui
    hostname: ui
    depends_on:
      - zookeeper
      - nimbus
    dns:
      - 192.168.33.20
    environment:
      SERVICE_NAME: ui
      NIMBUS_SERVICE_NAME: $nimbus
      ZK_SERVICE_NAME: $zookeeper
    command: --daemon ui

  supervisor:
    image: ogre/storm-docker:1.0.1
    #container_name: supervisor
    hostname: supervisor
    depends_on:
      - zookeeper
      - nimbus
    dns:
      - 192.168.33.20
    environment:
     SERVICE_NAME: supervisor
     NIMBUS_SERVICE_NAME: $nimbus
     ZK_SERVICE_NAME: $zookeeper
    command: --daemon supervisor